window.APP_CONFIG = {
  appTitle: "구영리 맛집 비교",
  areaLabel: "울산광역시 울주군 범서읍",
  activeRegionId: "guyeong",
  basePoint: { lat: 35.5761, lng: 129.1896 },
  basePointLabel: "UNIST 기준",
  bentoScope: {
    excludedDistricts: ["북구", "동구"],
    maxDistanceKm: 15,
  },
  usageTrend: {
    startMonth: "2025-01",
    endMonth: "2026-06",
    summaryMonths: 6,
  },
  publicDataSources: {
    "일반음식점": {
      label: "행안부 일반음식점",
      url: "https://www.data.go.kr/data/15045016/fileData.do",
    },
    "휴게음식점": {
      label: "행안부 휴게음식점",
      url: "https://www.data.go.kr/data/15006730/fileData.do",
    },
  },
  regions: [
    {
      id: "guyeong",
      name: "구영리",
      areaLabel: "울산광역시 울주군 범서읍",
      center: { lat: 35.5724, lng: 129.2417 },
      bounds: [129.2325, 35.562, 129.2515, 35.579],
      excludedNames: ["막끌리네", "갓포HERO"],
      searchTokens: ["구영", "구영로", "구영앞길", "점촌"],
      addressKeyPattern: "(구영로|구영앞길|점촌[0-9]*길|구영리)\\s*([0-9-]+)?",
      categoryOverrides: {
        "3730000-101-2023-00116": {
          category: "도시락",
          menu: "수제도시락, 박스케이터링, 케이터링, 배달",
          source: "네이버 플레이스",
          sourceUrl: "https://map.naver.com/p/entry/place/1441522000",
        },
        "3730000-101-2013-00034": {
          category: "도시락",
          menu: "전복밥 도시락, 버섯밥 도시락, 곤드레밥 도시락, 스낵박스, 배달",
          source: "네이버 플레이스",
          sourceUrl: "https://map.naver.com/p/entry/place/32820747",
        },
        "3730000-101-2006-00181": {
          category: "도시락",
          menu: "출장조리, 단체식사, 케이터링",
          source: "행안부 인허가 업태: 출장조리",
          sourceUrl: "",
        },
      },
    },
    {
      id: "cheonsang",
      name: "천상리",
      areaLabel: "울산광역시 울주군 범서읍",
      center: { lat: 35.5628, lng: 129.2297 },
      bounds: [129.216, 35.551, 129.2425, 35.5735],
      searchTokens: ["천상", "천상리", "천상중앙길"],
      addressKeyPattern: "(천상중앙길|천상[0-9]*길|천상리)\\s*([0-9-]+)?",
    },
    {
      id: "gulhwa",
      name: "굴화리",
      areaLabel: "울산광역시 울주군 범서읍",
      center: { lat: 35.5503, lng: 129.2564 },
      bounds: [129.244, 35.539, 129.27, 35.56],
      searchTokens: ["굴화", "굴화리"],
      addressKeyPattern: "(굴화[0-9]*길|굴화리)\\s*([0-9-]+)?",
    },
    {
      id: "mugeo",
      name: "무거동",
      areaLabel: "울산광역시 남구",
      center: { lat: 35.5438, lng: 129.2609 },
      bounds: [129.245, 35.528, 129.278, 35.559],
      searchTokens: ["무거", "무거동", "대학로"],
      addressKeyPattern: "(대학로|무거[0-9]*길|무거동)\\s*([0-9-]+)?",
    },
    {
      id: "eonyang",
      name: "언양·삼남",
      areaLabel: "울산광역시 울주군",
      center: { lat: 35.555, lng: 129.13 },
      bounds: [129.05, 35.49, 129.21, 35.62],
      excludedNames: ["교동민속주점", "복순도가 울산역점"],
      searchTokens: ["언양읍", "삼남읍"],
      addressKeyPattern: "(언양읍|삼남읍|언양로|울산역로|교동로|반구대로|유니스트길)\\s*([0-9-]+)?",
    },
  ],
  categoryFilters: [
    { label: "전체", value: "all" },
    { label: "한식", value: "한식" },
    { label: "고기류", value: "고기/구이" },
    { label: "국밥/탕", value: "국밥/탕" },
    { label: "면류", value: "면/칼국수" },
    { label: "중식", value: "중식" },
    { label: "일식", value: "일식" },
    { label: "횟집류", value: "해산물/횟집" },
    { label: "양식", value: "양식" },
    { label: "치킨/피자/버거", value: "치킨/피자/버거" },
    { label: "분식", value: "분식/김밥" },
    { label: "베이커리", value: "베이커리" },
    { label: "카페", value: "카페/디저트" },
    { label: "기타", value: "기타" },
    { label: "도시락", value: "도시락" },
  ],
};
